<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Messages/*.*" />
    <EmbeddedResource Include="Messages/*.*" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Ivory.Soap/Ivory.Soap.csproj" />
    <ProjectReference Include="../Ivory.SoapApi/Ivory.SoapApi.csproj" />
    <ProjectReference Include="../Ivory.TestModels/Ivory.TestModels.csproj" />
  </ItemGroup>

</Project>
